// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFao-D9v6JSZI_3PkK7dQOO3gdqsaB-mc',
    appId: '1:782126340773:web:1ff85856827a13e55c0b4c',
    messagingSenderId: '782126340773',
    projectId: 'task-manager-b878f',
    authDomain: 'task-manager-b878f.firebaseapp.com',
    storageBucket: 'task-manager-b878f.firebasestorage.app',
    measurementId: 'G-Q0WKZQQYZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3eih6uDylRTNvu_XMn-ayliEihd2iJQ',
    appId: '1:782126340773:android:04fb8142d17fcb215c0b4c',
    messagingSenderId: '782126340773',
    projectId: 'task-manager-b878f',
    storageBucket: 'task-manager-b878f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYMtTO2CDcsavN2I66s8PyN-z0uxOWv-M',
    appId: '1:782126340773:ios:02abe039889242835c0b4c',
    messagingSenderId: '782126340773',
    projectId: 'task-manager-b878f',
    storageBucket: 'task-manager-b878f.firebasestorage.app',
    iosBundleId: 'com.example.classwork6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYMtTO2CDcsavN2I66s8PyN-z0uxOWv-M',
    appId: '1:782126340773:ios:02abe039889242835c0b4c',
    messagingSenderId: '782126340773',
    projectId: 'task-manager-b878f',
    storageBucket: 'task-manager-b878f.firebasestorage.app',
    iosBundleId: 'com.example.classwork6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFao-D9v6JSZI_3PkK7dQOO3gdqsaB-mc',
    appId: '1:782126340773:web:05a204ac0f661fae5c0b4c',
    messagingSenderId: '782126340773',
    projectId: 'task-manager-b878f',
    authDomain: 'task-manager-b878f.firebaseapp.com',
    storageBucket: 'task-manager-b878f.firebasestorage.app',
    measurementId: 'G-7HF3KX2PVX',
  );
}
